# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pr:
  - main

pool:
  name: Default

steps:
  - script: cmake -B build
    displayName: 'Configure'

  - script: cmake --build build
    displayName: 'Build'

  - script: |
      mkdir -p build/test-results
      cd build
      ctest --output-on-failure --output-junit test-results/results.xml
    displayName: 'Run Tests'

  - task: PublishTestResults@2
    displayName: 'Publish test results'
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'build/test-results/results.xml'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact'
    inputs:
      PathtoPublish: 'build/malloc_impl'
      ArtifactName: 'malloc_impl'
      publishLocation: 'Container'