# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: Default

steps:
  - script: cmake -B build
    displayName: 'Configure'

  - script: cmake --build build
    displayName: 'Build'

  - script: |
      cd build
      ctest --output-on-failure
    displayName: 'Run Tests'
    
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact'
    inputs:
      PathtoPublish: 'build/malloc_impl'
      ArtifactName: 'malloc_impl'
      publishLocation: 'Container'